network:
  version: 2
  renderer: networkd
  ethernets:
    enp1s0:
      addresses:
        - 192.168.2.200/24
      routes:
        - to: default
          via: 192.168.2.1
      nameservers:
          addresses: [8.8.8.8, 4.4.4.4]
